### ISSUE TITLE
Versioning and referencing of our specs

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#10]
@mimayer @cboisson, @joleroi, all - How should we version the specs here and obtain a stable reference URL?

The IRF specs are making good progress, I think we can finish this soon.
(days for a first version, then weeks to have some discussion with others)

@joleroi suggested that we do something similar to the OGIP specs, where a `HDU_DOC` keyword is used to refer to the specification:
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/ofwg_recomm/r8.html

I'm a bit hesitant to use the https://github.com/gammapy/gamma-astro-data-formats or http://gamma-astro-data-formats.readthedocs.org/ in `HDU_DOC` in FITS files, because the reference might not be stable enough (e.g. if we decide to move the repo or HTML page hosting for some reason).

Thus my suggestion would be that in early January we tag the repo with a 1.0 version and put it up on https://zenodo.org/ . Then we have a DOI, which is the most stable reference one can get as far as I know.

@zblz @giacomov @woodmd - We'll have to discuss whether it makes sense to keep the astro model specs (and other things I'd like specified, like input / output to sensitivity computations) in the same repo, or whether we split things out into separate repos where development / versioning can occur at a pace that's appropriate for each spec.

We don't have to decide these things now, I suggest we take some time until January to see how the different specs evolve and keep them all here for now.
But I wanted to start the discussion early and hear what you all think about versioning and referencing of our specs.

**Comment by cdeil** [comment]
This was discussed in a HESS FITS telcon today, in preparation of the CTA DATA meeting next week.

We decided that it's useful  0.1 version (git tag and DOI from Zenodo), so I'll do this on Friday:
https://github.com/gammapy/gamma-astro-data-formats/milestones/0.1

Everyone - Please help get the specs and narrative text into shape for the parts you are about!

**Comment by cdeil** [comment]
I've tagged the current master version because this is used in HESS, but there will be significant changes in the coming days. I do not plan to upload this version to Zenodo.

See 
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/releases/tag/v0.1 

This tag is picked up by readthedocs:
http://readthedocs.org/projects/gamma-astro-data-formats/versions/

But the version "v0.1" is not displayed correctly yet.
This needs to be implemented in the Sphinx build, e.g. by hand or using https://github.com/warner/python-versioneer .

**Comment by cdeil** [comment]
Moving all  issues from the 0.1 milestone to 0.2 now.

**Comment by cdeil** [comment]
We are preparing the first HESS FITS test data release, and want a stable and archived version of the specs.

We had v0.1 in April 2016 as a very preliminary version:
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/releases/tag/v0.1

I propose to make the next version in ~ 1 week, and to call it v0.2.
The reasoning for this is that it's still very preliminary and many things are not agreed, so v1.0 IMO sends the wrong message.
@mackaiver (from #33) and all - Is this OK for you, or would you prefer to call it v1.0

The other question is what edits are needed before the release. I see a few points at
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/milestone/2
but as far as I know, none of those are real issues and they could all be deferred to the the v0.3 milestone.
Is that correct, or is there something that should really be fixed or improved before v0.2?

Is anyone able to help out here, and do the technical work to get proper versioning of the spec, i.e. to git tag, and propagate the version to the docs page, and introduce a changelog, and eventually submit to Zenodo to get a DOI and have it archived. (see comments above, it needs someone that knows how to work with Sphinx and Readthedocs and git a bit to do this)

If I don't hear back here, I plan to do this and make a v0.2 release on Tuesday, May 8.

**Comment by TarekHC** [comment]
>  @mackaiver (from #33) and all - Is this OK for you, or would you prefer to call it v1.0

Ok by me.

**Comment by mackaiver** [comment]
👍

**Comment by cdeil** [comment]
All (especially @TarekHC @cboisson @lmohrmann @tony32lin ) - if you have time, please have a final look at the spec: https://gamma-astro-data-formats.readthedocs.io/

Adding proper versioning is the only task left before tagging v0.2 and uploading it to Zenodo. I plan to do that on Monday afternoon.

This will be the basis / reference for the HESS data release and joint Crab paper, so ideally we'd make it a nice and polished document. So if you notice some mistake or would like to change or improve something, please open an issue or PR before Monday noon.

**Comment by TarekHC** [comment]
Again, good to go from my side!

**Comment by cdeil** [comment]
At the moment we have version 0.2 in `conf.py` as well as several specs pages listing `HDUVERS`.
This is good enough for now, I'm tagging v0.2 now.

In the future, if this project continues, probably something better should be set up, to be clear and automate the process of updating version numbers semi-automatically. In Python projects things like 
 https://pypi.org/project/bumpversion/ or https://github.com/warner/python-versioneer are used, and they could be used here as well to get dev version numbers and automatic version handling.

So I'll keep this issue open for now, but remove it from the v0.2 milestone.
