### ISSUE TITLE
Background model specs

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#11]
@JouvinLea @mimayer - I've started to write the background model spec, can you please have a look:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/background/index.html

- [x] For the `bkg_2d` model, I prefer an axis that contains THETA values in deg, and not THETA_SQUARE values in deg^2, because a linear axis is simpler than one with a SQUARE or SQRT scale, and the OGIP aeff and PSF formats also always use THETA and RAD, and not square. We can / will still choose to create background models with a nice binning, probably equal-solid-angle bins. OK?
**==> Conclusion: use THETA**
- [x] @mimayer Does Gammalib / ctools need the column to be called "bgd" at the moment? I'd prefer we use "bkg" everywhere, and not sometimes "bgd". Should be easy to teach the Gammalib class to look for "bgd" or "bkg" for now? OK to have "bkg"?
**==> Conclusion: use "bkg"**
- [x] Any opinions on the energy unit of the bkg column i.e. "MeV-1" or "TeV^-1"? I'd prefer TeV since I think we use that everywhere else as far as I know. But I guess using MeV here has some good justification as well, i.e. what Fermi uses and what Gammalib uses at the moment. (in Gammapy I think we read and use the units, i.e. it doesn't matter to us, but I'm not even sure).
**==> Conclusion: use MeV so that it still works for Gammalib**
- [x] Do we want a 1D format to store acceptance curves (just THETA as an axis, for an integral energy band)? It's super common in HESS and we probably want to store / exchange / compare them with the HESS software, i.e. it's good to have a format, no?
**==> Conclusion: for now: no, can be added later.**

Any other comments / questions / suggestions for the spec?

**Comment by mimayer** [comment]
> For the bkg_2d model, I prefer an axis that contains THETA values in deg, and not THETA_SQUARE values in deg^2, because a linear axis is simpler than one with a SQUARE or SQRT scale, and the OGIP aeff and PSF formats also always use THETA and RAD, and not square. We can / will still choose to create background models with a nice binning, probably equal-solid-angle bins. OK?

Agree, the binning should be chosen for our purpose. Thus I would also recommend to stick to THETA and just adjust the binning to our needs.

>  @mimayer Does Gammalib / ctools need the column to be called "bgd" at the moment? I'd prefer we use "bkg" everywhere, and not sometimes "bgd". Should be easy to teach the Gammalib class to look for "bgd" or "bkg" for now? OK to have "bkg"?

I just checked and gammalib access the background cube by integer. Currently the first parameter cube that is detected is used. Therefore no specific name is needed. Agree to use "bkg"!

> Any opinions on the energy unit of the bkg column i.e. "MeV-1" or "TeV^-1"? I'd prefer TeV since I think we use that everywhere else as far as I know. But I guess using MeV here has some good justification as well, i.e. what Fermi uses and what Gammalib uses at the moment. (in Gammapy I think we read and use the units, i.e. it doesn't matter to us, but I'm not even sure).

At least for now I would be in favour to use MeV-1, since gammalib uses it as well. In the future supporting units would be helpful of course. So let's keep MeV for now.

> Do we want a 1D format to store acceptance curves (just THETA as an axis, for an integral energy band)? It's super common in HESS and we probably want to store / exchange / compare them with the HESS software, i.e. it's good to have a format, no?

Of course this can be an optional file, but I am not sure about the use cases (as acceptance varies intensely with energy). In my view 2D and 3D should be sufficient for analyses.

**Comment by cdeil** [comment]
@mimayer - Thanks for the feedback!

Concerning extra background models with other axes (e.g. 1D THETA or 2D DETX,DETY or 1D ENERGY) ... I think such background curves or images or spectra are interesting to look at and to compare between tools (e.g. the HAP results against Gammapy). But I'm also not so keen on writing more specs and implementing more classes in Gammapy for now. So I'm 50:50 on adding more info here ... can always be done later.

One more thought: to compute cubes one usually fills separate counts and livetime cubes, and only at the end computes the `bkg` rate.
Would it be useful to mention that these arrays can be stored as extra `time` and `counts` columns after the `bkg` column (optional)?
Could be useful to agree on this for cross-checking codes that produce background models?

FYI: Gammapy actually has an I/O format for the time and counts info ... I'd prefer to specify it here as optional extra columns (which is not how I think we store it at the moment, but it makes more sense to me than separate HDUs):
https://gammapy.readthedocs.org/en/latest/api/gammapy.background.CubeBackgroundModel.html

**Comment by mimayer** [comment]
I am not convinced about the use case for high-level analysis to export 1D Background curves. Maybe things like that can be kept invisible for the user and outside the FITS database?

In my view having lots of different background models, including information like counts and exposure maps is more debugging information which will be not really important to the user. In the end the user doesn't want to care too much about background modelling (need to specify the caveats though).

Actually, for checks on background modelling, I have added "NEVENTS" and "LIVETIME" keywords to the background models I exported for tests. These keywords allow the user to quickly check how much statistic was available to build a background model. We could think about adding this information to the FITS files, what do you think?

**Comment by cdeil** [comment]
What I proposed, optional COUNTS and LIVETIME columns, is just a bit more info than what you propose, NEVENTS and LIVETIME header keys, with the added advantage that the energy- and position-dependence of the available counts and livetime is known.

We could just add both!

I think it's convenient extra info to store (agreed: mainly for experts, not end-users) and optional things are just a convenience for people using such info to have more interoperable scripts (e.g. you use NEVENTS, we use COUNTS at the moment ... it means our scripts are incompatible for no good reason, e.g. maybe we want to cross-check results before the smoothing step or something.

**Comment by mimayer** [comment]
I guess for now this would be ok as we are having ~20 different background models. However, if someone comes up with creating a run-wise detailed background model, this debugging info would make the disk storage go through the roof. We currently have ~500kB per background model, multiplied by >15000 starts to get large.
Therefore I would be strongly in favour to not make this a requirement. Ok to make it optional. Keywords COUNTS and LIVETIME can be required or also optional?

**Comment by cdeil** [comment]
keywords also optional ... the required / optional decision should usually be based on "is this really needed for important use cases (=> required) or just nice to have / agree on keywords for experts (=> optional)"

**Comment by cdeil** [comment]
I'll update the bg spec page and then close this issue in the coming days.

**Comment by mimayer** [comment]
Ok!

I am still thinking wether a user might want/need this information what statistics was used to create the background model.

**Comment by cdeil** [comment]
I've done some cleanup to the background spec page in b64fa97

The current version is now here:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/background/index.html

For now I'm not adding a 1D format or info on optional header keys or columns.
I think this issue is fully addressed ... closing it now.
If you want to change or add something, please open a new pull request or issue.

The question of whether to stick with "MeV^-1" here or whether to change to "TeV^-1" for consistency or be flexible with the units is under discussion and will be adressed in future issues / pull requests.
See [here](https://github.com/open-gamma-ray-astro/2016-04_IACT_DL3_Meeting/blob/master/notes/2016-06-07-IACT_DL3_Telcon.md#minutes) for the recent discussion by @jknodlseder  and me.
