### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#114]
I think we should maybe add a license to this `gamma-astro-data-formats` to make it clear what kind of use is and isn't allowed.

This might be important especially if CTA wants to continue here or copy from here as the starting point for their internal data format specification effort. My understanding is that currently, it's legally not clear what use is allowed, CTA would have to contact the contributors here and ask permission before e.g. copying the spec as starting point for CTA-internal documentation.

Looking around a bit, e.g. at https://choosealicense.com/non-software/ or https://creativecommons.org/choose/ or e.g. https://github.com/elegant-scipy/elegant-scipy and https://github.com/jakevdp/PythonDataScienceHandbook as mixed code / text projects, one option could be that we put this:

- Code is BSD-3. (currently we just have a few Python scripts to generate example files using Numpy, Astropy and Gammapy, all BSD-3 projects)
- Text is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

These are very liberal licenses that are very permissive in re-use, even commercial.

@woodmd and @TarekHC  as biggest contributors here - OK?
@kosack  or anyone from CTAO - does this work for you?

**Comment by woodmd** [comment]
Sounds good to me.

**Comment by TarekHC** [comment]
I agree. We need a license, and the more open the better.

If we are sure that using BSD-3/CC BY 4.0 will not conflict with CTA (or ctapipe), then it's a good choice.
