### ISSUE TITLE
Explain  EVENT_TYPE column or remove

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#120]
From the specs:
```
EVENT_TYPE type: bit field (in FITS tform=32X)
        Event quality partition.
```

* Why is this a bitfield?
* What is the meaning of the 32 bits?
* What shall this column be used for?

**Comment by cdeil** [comment]
This EVENT_TYPE came from the original event spec by @kosack . Karl, maybe you can comment?

Fermi also has EVENT_TYPE, but I think they use INT , not BITFIELD?
See my comment here: https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/119#issuecomment-408022392
Probably we should add a glossary entry explaining what the idea behind event type is (same as Fermi).

@MaxNoe or anyone - If you have time to send PRs for the spec, that would be great. If not I'll try to address these comments soon.

**Comment by cdeil** [comment]
For IACTs or any data, the idea is that the definition of event class and type are left to the instrument. EVENT_CLASS is provenance, or possibly used when looking up IRFs in a CALDB (not specified yet).
EVENT_TYPE is not used by science tools at the moment, but in the future could be in a similar way as Fermi, i.e. to associate with IRFs and have multiple types in a joint analysis.

**Comment by MaxNoe** [comment]
> If you have time to send PRs for the spec 

I would like to. However, I have no Idea what this field is supposed to contain, this is why I created this issue.

**Comment by cdeil** [comment]
I tried to address this issue. See https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/116#issuecomment-408611796

I don't think I can explain it better. It's just a few people that are starting to prototype and use ``EVENT_TYPE``, really defining it in the spec and using it like e.g. Fermi-LAT did is future work that will likely take another 1-2 years.

OK?

Closing this issue now. If you have a specific suggestion for a change, or to improve the explanation, please re-open or send a PR or open a new issue.
