### ISSUE TITLE
Optional column for a gammaness value

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#121]
Most experiments assign each event a score that represents how likely an event is a gamma-ray. (which is not-necessearily or even more commonly not a probability)

I think there should be an optional column in the standard for this parameter and possibly also responses for different thresholds in this parameter.

**Comment by cdeil** [comment]
See #34 .

Can you please look at that, and if you think for v0.2 something should be added or changed, send a PR?

Otherwise I'd suggest you comment on #34 and we close this one as duplicate and leave #34 open as future work.

**Comment by cdeil** [comment]
Closing this issue now. Let's continue the discussion in #34 .
