### ISSUE TITLE
Provide docs for all versions

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#123]
The docs page should provide a possibility to select the version and make clear what the currently displayed version is (v0.1, dev)

**Comment by cdeil** [comment]
This already exists. The only stable version we have so far is https://gamma-astro-data-formats.readthedocs.io/en/v0.1/ , v0.2 coming very soon.

Readthedocs creates a version choose widget in the lower-left corner, as can be seen in this current screenshot:

![screen shot 2018-07-29 at 13 39 41](https://user-images.githubusercontent.com/852409/43365946-05581b20-9335-11e8-8d68-cb3ffef07be9.png)

Note that having a version number (including dev version and date) in the docs, and the rendered PDF is harder. I plan to do this next week, for that, #10 is still open.

Closing this issue now.
