### ISSUE TITLE
Release version 0.2

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#129]
This issue is to keep a record of the version 0.2 release process.
It might be useful to see the steps if someone else in the future wants to cut a v0.3.

- [x] I've already set the version number in conf.py to "0.2" in #128
- [x] git tag "v0.2"
- [x] Update readthedocs so that the new stable version shows up there
- [x] archive on zenodo
- [ ] some edits / updates, e.g. change version to "0.3.dev" in conf.py and mention zenodo somewhere, e.g. in the README.

**Comment by cdeil** [comment]
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/releases/tag/v0.2

**Comment by cdeil** [comment]
- https://gamma-astro-data-formats.readthedocs.io/en/v0.2/
- https://media.readthedocs.org/pdf/gamma-astro-data-formats/v0.2/gamma-astro-data-formats.pdf

**Comment by cdeil** [comment]
I have set up this repo in Zenodo so that it's auto-linked and a new Zenodo archive will be made for each stable version (see https://guides.github.com/activities/citable-code/ and https://help.zenodo.org/).

I didn't find a way to get Zenodo to make a record for the https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/releases/tag/v0.2 that I tagged and released just before, because I thought I could do Zenodo as the next step after. I'll try deleting that release (but not the git tag) now, and see if that gets Zenodo to do it's thing.

**Comment by cdeil** [comment]
This kinda worked, there's something on Zenodo now.

It was very confusing to edit the metadata for this publication. I think there's one for all versions that will change over time ( https://zenodo.org/record/1403880 ) and one specifically for version 0.2 ( https://zenodo.org/record/1403881 )

I still don't see an option to upload extra files. I'd like to upload the PDF and also generated HTML to make it easily accessible. And I'd like to put a different description for v0.2 or the overall project.

!?

**Comment by cdeil** [comment]
I have sent a support ticket to Zenodo, asking them to add the PDF and HTML files to https://zenodo.org/record/1403881 , or alternatively to delete that record and let me start over with a "normal" record where I can upload any files I like.

cc @TarekHC @cboisson @cosimonigro @Bultako

**Comment by Bultako** [comment]
@cdeil

What I understand from Zenodo is that you may either create and edit the content of a Zenodo repository using Zenodo infrastructure or link to the content of a Github repo, but not both options a the same time. What I would do is to add PDF and HTML documentation into the Github repo just before labelling a stable released. 

Alternatively, you could add a link to the RTD documentation, in the description of the Zenodo record. 

Re: Tracking Github releases with Zenodo

I think this works as a Github webhook, only future releases are tracked as versions when one labels a new release in Github. The non-versioned general DOI identifier points to the latest one.

---

I don't know if linking to Github is a good option for a paper/documentation with no relevant code behind. What is really important in this case is the text itself, not the Sphinx config files neither the RST files in markdown format. Note that Zenodo links to specific labels/releases in GH, not to the *living docs*, but to a a very specific snapshot taken in the past.

Zenodo gives you the option to upload a document in any format i.e. PDF, and provides a versioned DOI for that document.  I would create a new Zenodo repo and upload v0.1 pdf file, create a new version with v0.2 pdf file, and do the same for next versions, maybe saying in the description that the *living docs* are in GH or RTD.

**Comment by cdeil** [comment]
@Bultako - Thanks!

I agree, if it's not possible to add extra files and notes per release, it was a mistake to use the "DOI versioning" from Zenodo (see desription at https://help.zenodo.org/).

I'll wait for Zenodo help desk to reply, hopefully they can still remove the submission.

And then probably I'll make a "normal" entry and remove the auto-link to Github for this repo.

**Comment by cdeil** [comment]
The records have been removed by Zenodo support, and I have set the auto-link for this repository to OFF in the Zenodo settings.

I will make a normal Zenodo upload for the spec in the next days.

**Comment by cdeil** [comment]
I made a new upload on Zenodo: https://doi.org/10.5281/zenodo.1409830

**Comment by cdeil** [comment]
I've set the master to version 0.3.dev in 022cbd3 and added some info for the stable versions and v0.2 specifically to the README in 9627815 . Closing this issue now.
