### ISSUE TITLE
Transfer of power

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#136]
In #135 @lmohrmann brought up again the important question how to handle IRF errors.
This was discussed quite extensively in ~ 2016 when we worked on CTA DL3, it's listed as "IRF validity ranges, errors" [here](https://arxiv.org/pdf/1610.01884.pdf). There's also the related #68 open with an old suggestion from me that IRF smoothing should be the pipeline's responsibility and science tools should be able to assume to get smooth IRFs. As far as I know, there has been little to no progress on this in the past 2 years.

This I am leaving astronomy in December, and no longer have time to work on this.
I will still work in Gammapy for a bit and respond at https://github.com/gammapy/gammapy/issues/2432 .
I'm unsubscribing from all notifications in the https://github.com/open-gamma-ray-astro/gamma-astro-data-formats issue now. I just wanted to make it clear that you shouldn't expect any reply or further improvements from me.

I added a few of as owners for this Github org and repo, so you can continue to work either in the open or within CTA as you see fit. In my experience, the problem has always been to get contributions at all, not that someone puts crazy or bad things. In 2016, we first envisioned that either there would be a group of stakeholders (from CTA, HESS, Fermi, Gammapy, ctools at least) and drive this effort. Now I think probably CTAO will start up a new internal development process for DL3, and whether this open spec effort continues or where it goes is completely unclear.

To quote [Guido](https://mail.python.org/pipermail/python-committers/2018-July/005664.html): "So what are you all going to do?"

@cboisson @kosack @MatthiasFuessling @robertazanin @adonath @registerrier @jknodlseder @jimhinton @lmohrmann  - All the best!

**Comment by kosack** [comment]
Thanks for all the great work @cdeil !
