### ISSUE TITLE
Write time spec

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#14]
I'm out of time for today, but I want to write up the time spec soon:
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/time.html

I don't think there's anything controversial, we'll have MET, MJD and UTC time strings.

**Comment by kosack** [comment]
make sure you also provide a guide to when/why each one is used.  E.g for things that need high precision, use MET as one (2?) double(s),  whereas human readable things should be in ISO UTC, etc.

**Comment by cdeil** [comment]
Yes, I'll explain this briefly and then ping you to review that (short) page.

**Comment by cdeil** [comment]
I've started to write some info on times:
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/time.html

@kosack - Concerning precision, how about this?
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/time.html#precision

**Comment by cdeil** [comment]
I'm closing this old issue.

We now have this, which looks good to me:
http://gamma-astro-data-formats.readthedocs.io/en/latest/general/time.html

Specific new issues with suggestions are of course welcome any time.
