### ISSUE TITLE
Use observatory location definition as defined in the FITS standard

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#148]
Section 9.3.2 reads:

> In order to provide a complete description, ’TOPOCENTER’ requires  the  observatory’s  coordinates  to  be  specified.  
> Thereare  three  options: 
> * (a) the  ITRS  Cartesian  coordinates  defined in  Sect.  8.4.1  (OBSGEO-X,OBSGEO-Y,OBSGEO-Z),  which  are **strongly  preferred**;
> * (b) a  geodetic  latitude/longitude/elevationtriplet (defined below);
> * (c) a reference to an orbit-ephemeris file.
> 
>  A set of geodetic coordinates is recognized by the followingkeywords. 
> * OBSGEO-B  [floating-point] The  value field  of  this  keyword shall contain the  latitude  of  the  observation  in  deg,  with North positive.
> * OBSGEO-L  [floating-point] The  value field  of  this  keyword shall contain the longitude of the observation in deg, with East positive.
> * OBSGEO-H  [floating-point] The  value field  of  this  keyword shall contain the altitude of the observation in meters.
> An orbital-ephemeris file can instead be specified. 
> OBSORBIT  [string] The value field of this keywordshallcon-tain the character-string URI, URL, or the name of an orbit-ephemeris file

We should probably replace GEOLON / GEOLAT / ALTITUDE

**Comment by lmohrmann** [comment]
...and simply rename to OBSGEO-B / OBSGEO-L / OBSGEO-H?

**Comment by MaxNoe** [comment]
Yes, or encourage the geocentric values `OBSGEO-{X,Y,Z}`

**Comment by lmohrmann** [comment]
At least in HESS we currently use GEOLON/GEOLAT/ALTITUDE, so I would definitively like to keep this as one option. I don't have objections to renaming if the standard has changed.

**Comment by MaxNoe** [comment]
Encouraging one and forbidding the other are not the same thing. We should stick to the standard.
We could even in the software still fallback to GEOLAT/GEOLON/ALTITUDE if the other keywords are not present.

> HESS we currently use GEOLON/GEOLAT/ALTITUDE

That's not really an argument, as these files should specify that they are in accordance with standard v0.2 and that won't change anymore, right? 
So when the next standard is ready, you anyway need to update the software, make the necessary changes and write the v0.3 standard.

**Comment by lmohrmann** [comment]
Sure. All I'm saying is that I'd still like to have the geodetic coordinates mentioned in the specs, also if geocentric coordinates are encouraged.

**Comment by MaxNoe** [comment]
Yes sure. I'll open a PR which basically refers to the spec in the FITS Standard. I do like the geodetic coordinates more myself, as they are vastly easier to interpret. (at least I cannot do anything with geocentric coordiantes in my head.)
