### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#149]
This project should have a license.

As it is not directly code, CC would probably most approrpiate.

As it is a standard, it should not be modified.

So I would propose CC by Attribution, No-Derivatives:
https://creativecommons.org/licenses/by-nd/4.0/

**Comment by lmohrmann** [comment]
This sounds like a good proposal to me. Thoughts by anyone else?

**Comment by tibaldo** [comment]
Do you need to verify that the format license does not conflict with the licenses of the any Science Tools using the format?

**Comment by lmohrmann** [comment]
Another thought: this is supposed to be a prototype for the CTA data format, although it will of course be for CTAO to decide which format they will use. Nevertheless, we should make sure that a license does not prevent CTAO from building upon this work. I'm not an expert on licenses, so I don't know if this could be a problem or not.

**Comment by lmohrmann** [comment]
Also, see the previous issue #114

**Comment by MaxNoe** [comment]
Ok, sorry for not checking before opening this one. Seems they came to the same conclusion. BSD for code and CC BY for the license text. I'll open a PR.
