### ISSUE TITLE
ADASS presentation on the OGADF and the projects using the format

### ISSUE THREAD

**Issue by cosimoNigro** [open-gamma-ray-astro/gamma-astro-data-formats#163]
Hello, 

sorry to open an issue here, I thought it might be the most efficient way to get in touch with the people using/working with the open gamma ray astro data format. 
I will also send an e-mail to open-gamma-ray-astro@lists.nasa.gov though I think some of the people active here are not registered to it.

As you might know in November there will be the ADASS conference 
https://adass2020.es
and I thought it would be relevant to give a general talk on the open gamma-ray data format and its applications.
We had in the last couple of years several public (and published) projects using it, among them:
- the first H.E.S.S. DL3 data release
   https://arxiv.org/abs/1810.04516
- the joint-crab paper
   https://arxiv.org/abs/1903.06621
- the analysis of the DL3 HESS data with ctools 
   https://arxiv.org/abs/1910.09456
- the validation of gammapy and ctools with the same data
  https://arxiv.org/abs/1910.08088

I think the OGADF is by now a relevant piece of data standardisation for what concerns astronomical software.
Why not presenting the format and the projects employing it together?
I am sure it will be an important review talk in the context of the conference.

Who has registered for the conference? I have. And I am pretty sure @adonath is also going to present gammapy.
Anyone else (so we can choose a presenter)?

Apologies for the short notice, I submitted another talk today and had this idea while submitting.
The deadline for submission is **September 15**, let's see if you think it's a good idea and if we reach some consensus over the weekend and Monday.
 
If you had already planned to present the data format or one of these projects on your own just let me know.

Thank you, 

Cosimo

**Comment by MaxNoe** [comment]
Sounds good to me!

**Comment by Bultako** [comment]
Thanks @cosimoNigro for triggering this initiative and discussion.

We at ADASS are receiving much more contributions than I expected from the gamma/IACT community. At this moment it should be around ~20-25% Each contribution will be linked to one of these [themes](https://adass2020.es/themes/) and the program should in principle keep more or less the same weight for each theme. Up to now there's not a big number of talks for Data Interoperability, but there's even less on BoFs (Birds of a Feather). BoFs are informal discussions on a specific topic but also general enough to gather the interest of a community inside ADASS. They have a duration of 60 min, 15-20 min of presentation and 40 min of informal  discussion. I think this BoF format can be good to present the status of OGADF and gather feedback.

**Comment by lmohrmann** [comment]
Hi,
thanks for bringing this up. I'd certainly support a presentation, although I'll most likely not have time to help a lot in preparing it. If I can/should contribute anything about the Gammapy/ctools validation paper, let me know.

**Comment by cosimoNigro** [comment]
Hello, 

since the submission deadline is tomorrow, I submitted a proposal for a BoF talk (as @Bultako suggested). 
The submitted text can be modified, so we can iterate over it. 
@Bultako, I suggested you as additional speaker since no one has yet replied in this thread confirming his/her attendance to the meeting.

You can read the submitted abstract here
https://pretalx.adass2020.es/adass2020/talk/review/ALQKAEXVQUTRMNVU9ECRPRQH7KE78ZMS
and are invited either to modify it directly or to comment here on changes you'd like to see implemented.

Thanks!

**Comment by MaxNoe** [comment]
Some small comments:

> currently developed

are currently developing or have recently developed

> datas
datasets, data has no plural

**Comment by cosimoNigro** [comment]
Fixed, thanks.

**Comment by cosimoNigro** [comment]
Hello, the application for the presentation has been accepted.

**Comment by cboisson** [comment]
Good news,  and timely.

**Comment by cosimoNigro** [comment]
Hello everybody,
I am working on the slides and have a question:
was there a specific meeting within which this project was started (any CTA meeting, PyGamma15, ...)?
I wanted to give a reference for the start of the project, anyone remembers an occasion or a date?
Thanks!

**Comment by adonath** [comment]
@cosimoNigro Yes, the GADF initiative evolved form the PyGamma15 conference. There is still the website and repo:
- http://gammapy.github.io/PyGamma15/
- https://github.com/gammapy/PyGamma15

However I couldn't find any references such as minutes or similar that documented from which discussion GADF started...

**Comment by cosimoNigro** [comment]
Thanks @adonath, @TarekHC pointed me to this
https://libraries.io/github/open-gamma-ray-astro/2016-04_IACT_DL3_Meeting
here I see some actual presentation and discussion on DL3.
Checking the history of the GADF repo itself it seems it was started in 2015, so I guess I'll quote both.

**Comment by cboisson** [comment]
you can have a look at the arxiv paper 1610.01884 by Christoph Deil et al

**Comment by cosimoNigro** [comment]
Hello,

at [this link](https://www.overleaf.com/6845198221dmzzpnzjkfvv) you can find the proceeding for our session at the ADASS XXX.
If some point has not been properly discussed let me know.
I put mine and Tarek's name on it (we will be presenting the session) adding  "on behalf of the _Data Formats for Gamma-ray Astronomy_ forum contributors". 
The papers describing the format and using it are properly acknowledged, so I think other people's work is properly recognised. If you disagree or are dissatisfied with this choice (and want your name to be explicitly mentioned) let us know.

The submission deadline is the 31st of October, so you have **this week** (let's say until Friday 30 at night) to provide comments. You can directly comment or edit the file at your convenience, keep in mind though the limit for ADASS proceedings is 4 pages.

As for the slides, me and @TarekHC are working on them and will circulate them soon. 
Our talk will be on the 11th of November, so for that we have more time.

Thanks.

**Comment by cosimoNigro** [comment]
Hello,

[at this link](https://www.overleaf.com/8428731164nmkzyttyxjft) you can find the slides for BoF session.
Me and Tarek will give the presentation on the 11th November in the morning.
You can provide comments until the 7th of November. 

Let me know if the different projects have been properly represented in the presentation.

You can make minor modifications directly in the overleaf, make a comment there in case you'd like to request major changes.

Thanks

**Comment by cosimoNigro** [comment]
Hello,

yesterday I gave the presentation.
The experience was positive and there was a lot of discussion with radio astronomers you can find [here](https://drive.google.com/file/d/1sg6MykX0tM1Bal759C92RxardJ6bEiwC/view?usp=sharing) the conference chat on this topic; [here](https://www.youtube.com/watch?v=rPb22usn7hU&t=2h43m25s) the video recording of the session.

I am closing the issue.

Thanks
