### ISSUE TITLE
Required axis order and make clear how axis order is defined

### ISSUE THREAD

**Issue by maxnoe** [open-gamma-ray-astro/gamma-astro-data-formats#166]
The FITS standard uses axis definion (stored in the `TDIMX`) keyword contrary to e.g. numpy.

In numpy, the shape of an array goes from slowest varying (outer most dimension) to fastest varying (inner most dimension).

The FITS standard uses the exact opposite definition for TDIM.

We should clarify which order we mean in the documentation.

Also, if the axis order is only recommended, how is the actual axis order specificed? By the order of the columns?

**Comment by MaxNoe** [comment]
It is currently very confusing at least for gammapy, as it seems that it expects 
a different array in the file than when directly instantiated:

https://docs.gammapy.org/dev/api/gammapy.irf.EffectiveAreaTable2D.html#gammapy.irf.EffectiveAreaTable2D

**Comment by maxnoe** [comment]
I saw that some files are using a `CREF` header attribute to specify axis order like so:

`CREF   = (ENERG,THETA)`

But I could not find **any** documentation on this. `CREF` is not a reserved fits header keyword.

Where does this convention come from? Any references for this? If it is just our invention, why is it not documented in the specs?

Do science tools support this?

**Comment by maxnoe** [comment]
Seems like I just missed the definiion in `irf axes` section of the docs, sorry for the spam
