### ISSUE TITLE
Organisation / maintaining GDAF

### ISSUE THREAD

**Issue by GernotMaier** [open-gamma-ray-astro/gamma-astro-data-formats#176]
This might be a very stupid question, but is there some kind of organisation or responsible person/maintainer behind GDAF?

 We are discussing steps towards using GDAF in regular production in VERITAS, which means that some kind of planning is necessary.

- what is the way to find consensus on changes?
- how are releases planned and organised?
- there are 43 open issues (some of them from 2015) and 4 pull requests. Some issues seem to be outdated, but others are definitely important. Is there a plan to handle that?

I am completely aware that this is a complex endeavor (different observatories, science tools, etc) - because of that it is important have some clearly outlined paths for changes and releases.

...and don't give me the answer that we should wait until CTAO takes this over... :-)

**Comment by maxnoe** [comment]
@GernotMaier As announced on the mailing list (which is linked in the README, so you can subscribe if you haven't yet) we want to organize a meeting after the summer break to exactly discuss this issue and setup some form of governance with representatives from each of the interested parties.

**Comment by GernotMaier** [comment]
Very good to hear and I am happy to join for this meeting.
(also will try to join the mailing list, as soon as the link works).

**Comment by bkhelifi** [comment]
Very few has received this email. One should maybe enlarged the diffusion... 
I will joint the NASA mailing list when it will work.

**Comment by maxnoe** [comment]
> (also will try to join the mailing list, as soon as the link works).

Seems the NASA mailing list server is down, let's hope its only temporary. I couldn't find contact info for that.

**Comment by GernotMaier** [comment]
(I am closing this issue, as further information is distributed through the mailing list)
