### ISSUE TITLE
Make a final release before handing over to VODF?

### ISSUE THREAD

**Issue by maxnoe** [open-gamma-ray-astro/gamma-astro-data-formats#192]
Should we make a final 0.3 release with the current changes to accomodate wide-field instruments?

I would be in favor, as there are already files floating around using these changes and some support is implemented in gammapy.

These are changes since 0.2:

https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/compare/v0.2...master

**Comment by maxnoe** [comment]
Then main changes are:

* Following the FITS standard for observatory location (OBSGEO-{X,Y,Z} or OBSGEO-{B,L,H}) instead of OGIP (GEOLAT, GEOLON, ALTITUDE)
* Changes regarding wide field instruments (OBS_MODE, changes from required to optional columns)
* Adding RAD_MAX in the HDU index table


To minimize the changes, we could also think about reverting the first one (OBSGEO-X vs GEOXXX).

**Comment by maxnoe** [comment]
So my first proposal would be:

* revert the observatory location change
* make the 0.3 release

**Comment by lmohrmann** [comment]
Why revert the observatory location change? So as not to invalidate files that have been produced without taking into account this change?

In any case, I would be supportive of doing a release, it's been a long time since we had one.

**Comment by maxnoe** [comment]
> So as not to invalidate files that have been produced without taking into account this change?

Just to keep the amount of work in the science tools for supporting 0.3 (and supporting 0.2 and 0.3 at the same time)  minimal.

It's a hard breaking change since it requires different keywords and different data representation to go with the recommended mode.

**Comment by maxnoe** [comment]
Maybe @adonath , @registerrier can comment for the gammapy side, @jknodlseder or @tibaldo for ctools

**Comment by adonath** [comment]
Thanks @maxnoe!  I completely agree it is time for another v0.3 release here. In Gammapy we already added support for some of the additional meta data (`OBS_MODE` and `RAD_MAX` table) in-officially but it would be great to have that tagged by a version number. In Gammapy we do not have a scheme to support multiple versions of GADF in the API (this means users cannot chose the version), however in practice we already support both v0.2 and v0.3. I think this is fine from our side.

I guess this will affect some of the data stored `gammapy-data`, which already includes the additional meta data but not an updated version tag. So I'll CC @LauraOlivera and @cosimoNigro here.

**Comment by maxnoe** [comment]
@adonath Yes, these "in-between" files should be updated to have the released version they follow.


Let's say we make the release on friday this week, 2022-09-30, so there is some time left for comments.

**Comment by adonath** [comment]
@maxnoe Sounds good to me!

**Comment by maxnoe** [comment]
Sorry, completely forgot about this. Since there were now further comments (in even one week more than announced) I am now going to press the release button.

**Comment by maxnoe** [comment]
Release is made now, finally. We still need to figure out the zenodo, but I will close this here
