### ISSUE TITLE
Documentation not updated to version 0.3

### ISSUE THREAD

**Issue by GernotMaier** [open-gamma-ray-astro/gamma-astro-data-formats#196]
https://gamma-astro-data-formats.readthedocs.io/ is pointing to https://gamma-astro-data-formats.readthedocs.io/en/v0.2/ , but I think it should point to the most recent release https://gamma-astro-data-formats.readthedocs.io/en/v0.3/

**Comment by maxnoe** [comment]
Thanks @GernotMaier, fixed now. It might need a browser restart though for you to see it.
