### ISSUE TITLE
GLON_PNT and GLAT_PNT should be required columns in the obs-index table

### ISSUE THREAD

**Issue by mimayer** [open-gamma-ray-astro/gamma-astro-data-formats#27]
For background modelling in particular it is important to e.g. to exclude runs from the galactic plane.
In general, to facilitate the observation selection in Galactic coordinates, "GLON_PNT" and "GLAT_PNT" should be required columns in the obs table!

**Comment by cdeil** [comment]
The current [obs index table spec](http://gamma-astro-data-formats.readthedocs.org/en/latest/data_storage/obs_index/index.html) has `RA_PNT` and `DEC_PNT` as required columns, and doesn't mention `GLON_PNT` and `GLAT_PNT`.

My preference would be to make `GLON_PNT` and `GLAT_PNT` optional.
Reasoning: `GLON` / `GLAT` can be computed easily from `RA`, `DEC`, and generally the guideline for required fields should be that they are required for many use cases.

This would imply that scripts working with obs index tables should always read `RA_PNT` and `DEC_PNT` and compute `GLON` / `GLAT` on the fly if needed for run selection. I think that's a fine solution and had planned to change the Gammapy script doing the offplane run selection you mention as a use case to work this way (see current version that accesses `GLAT` and fails for some of the existing obs tables [here](https://github.com/gammapy/gammapy/blob/master/gammapy/scripts/background_model.py#L111)).

@mimayer, @jknodlseder - Thoughts?

**Comment by lmohrmann** [comment]
We have added GLON_PNT and GLAT_PNT to the HAP exporters today. As far as we can tell, it appears to work well. The values appear in the events file header and the obs-table file.

**Comment by mimayer** [comment]
Excellent!

**Comment by cdeil** [comment]
My preference is to make these columns optional. But if others prefer to put them as required, that's fine with me as well. We have bigger fish to fry...

@mimayer - Maybe you could wait one more day to see if others have an opinion, and then add it to the spec?

**Comment by jknodlseder** [comment]
No real opinion on this, but make sure that if you specify things in RA/DEC you always have somewhere (e.g. the header) the epoch information that is needed for coordinate transformations.

The other question is if the scheme should support also pointing that change with time (slew observations)?

**Comment by cdeil** [comment]
> No real opinion on this, but make sure that if you specify things in RA/DEC you always have somewhere (e.g. the header) the epoch information that is needed for coordinate transformations.

Our current spec says RA / DEC is ICRS, and ICRS doesn't require epoch:
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/coordinates.html#ra-dec

> The other question is if the scheme should support also pointing that change with time (slew observations)?

I think eventually yes, this should be supported.
But no-one has worked out a data model / format for that, right?
So for now, my suggestion would be that we add a section somewhere stating that this use case isn't supported by out current scheme (and pull requests for a better scheme are welcome).
OK or do you want to start on this now?

**Comment by jknodlseder** [comment]
I guess then we should add a keyword RADECSYS='ICRC' to the header.

About the slew observations: the point is that the data model could be quite different for slew observations, and ideally you'd like to have a data model that supports target and slew observations. Maybe something that we should discuss during the DL3 meeting.

**Comment by cdeil** [comment]
> I guess then we should add a keyword RADECSYS='ICRC' to the header.

Yes.

> About the slew observations: the point is that the data model could be quite different for slew observations, and ideally you'd like to have a data model that supports target and slew observations. Maybe something that we should discuss during the DL3 meeting.

Yes, the data model and also the science tools will be different from what we have now to compute fluxes from slew observations.

**Comment by cdeil** [comment]
In #59 I've added optional columns for Galactic coordinates to the EVENTS and observation index spec to address this issue.

For the record: @mimayer was in favour of having them required in the obs-index, I was in favour of having them optional and no-one else voiced an opinion.

I'm closing this now, but of course pull requests proposing other changes are welcome.
