### ISSUE TITLE
Proposal for Semver and DOI

### ISSUE THREAD

**Issue by mackaiver** [open-gamma-ray-astro/gamma-astro-data-formats#33]
I propose to adhere to some semantic versioning standards. 
[semver 2.0](http://semver.org/) is a popular choice for many projects.

We can use [digital object identifiers](https://guides.github.com/activities/citable-code/) for linking to stable versions of the spec via github releases.

**Comment by cdeil** [comment]
@mackaiver - I'm closing this issue as duplicate. Let's use #10 to keep the discussion in one place.

**Comment by cdeil** [comment]
https://0ver.org/ 

😺

**Comment by cdeil** [comment]
Forgot to close this issue. Let's keep the versioning discussion in one place: #10.
