### ISSUE TITLE
Support for multiple responses (specifically point-like AEFF and EDISP)

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#71]
The current spec has some support for multiple responses via the `HDU_CLASS` key in the index files.
See http://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/hdu_index/index.html#hdu-type-and-hdu-class

Specifically for AEFF we do support two versions via the keyword `HDUCLAS2={'EFF_AREA', 'EFF_AREA_RECO'}`
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/effective_area/index.html

This is not yet supported in the HDU index file format, there's just one key `HDUCLASS='aeff_2d'` defined, so it's not possible to access both AEFF via the current index file.

In HESS, in addition now we have the use case of wanting to define and access AEFF and EDISP derived from point-like responses (with a `RAD_MAX` cut applied) or full-enclosure responses.
Using point-like responses is very common (in HESS it's used e.g. for all AGN analyses), and we'd like to start using it for FITS analyses.
Note that there is a difference (demonstrated in HESS by @bkhelifi), EDISP is worse for events in the PSF tail, so it's not possible to get the correct EDISP from the full-enclosure responses at a high accuracy level, as another argument that we should support point-like responses in the DL3 spec.

So we would like to  extend the IACT DL3 format spec to support point-like IRFs.

Our main questions are:

- Which AEFF and EDISP header keys should we use?
- How should we support this via the HDU index file?

For the two different AEFF we started to use `HDUCLAS2={'EFF_AREA', 'EFF_AREA_RECO'}`
So we could use `HDUCLAS3={'point-like', 'full-enclosure'}` and add the `RAD_MAX` header key that's already in AEFF to EDISP also.
And then add HDUCLAS2 and HDUCLAS3 columns to the index file spec.
This would satisfy the current use cases for HESS.
It's not very pretty though, because point-like/full-enclosure is not really at a lower or higher level in the hierarchy compared to whether AEFF and EDISP were combined or not. It's just different ways to do responses / analysis.

Another option would be to change the `HDUCLASS` valid keys to `aeff2d_point_reco`, `aeff2d_fullenclosure_reco`, aeff2d_point_true`, `aeff_fullenclosure_true` instead of adding new columns.

Another option would be to replace the `HDUCLASS` column with a TAGS column which has a string that is a list of key-value fields, like `HDU_CLASS="point=yes,energy=reco"` which is super-easy to parse and then scientists or science tools can do selections based on that.

Or directly go to a hierarchical index format instead of sticking with the table.
IMO that would be the best mid-term solution (next year) to develop such a new, better format.
But short-term, my suggestion would be to either add columns or string cases to the existing index file format.

@kosack @mimayer @TarekHC @bkhelifi @registerrier @joleroi  @jknodlseder - Thoughts?

(if no-one comments on this, I will probably go ahead and make a pull request adding extra optional columns to the HDU index file next week)

**Comment by TarekHC** [comment]
Hi @cdeil ,

In my opinion, I would go for option 1: ``HDUCLAS3={'point-like', 'full-enclosure'}`` (or analogous keywords) This is exactly the use case for ``HDUCLASn`` keywords. 

> It's not very pretty though, because point-like/full-enclosure is not really at a lower or higher level in the hierarchy compared to whether AEFF and EDISP were combined or not. It's just different ways to do responses / analysis.

I don't really see why not. Currently ``HDUCLAS2`` defined which "type" of effective area you are storing, and ``HDUCLAS3`` could fix how it was calculated. Seems reasonable to me (by the way, ``HDUCLAS1`` is not written in the current specs).

And by the way, in MAGIC we would definitely be interested to also have a "point-like" DL3 format... Also for CTA it would make sense to perform a MC point-like source simulation when observing AGNs...

**Comment by bkhelifi** [comment]
Hi @TarekHC ,

I am happy that the point source analysis is not discarded! It provides a good S/N ratio and more sensitive analysis configurations...

To come back to the posted question, I do not see what is a 'type' of effective area... The use of reco or true energy is related to the algorithm used to fit the spectra. The use of Point-Like effective area or Full Enclosure one is related to an analysis configuration choice, with its own sensitivity and systematics. And of course, every combination (here 4 possibilities) can be chosen.
So, for me, there is no hierarchy between these attributes, all bringing different types of informations.

Personally, I like the 'TAG' option, bringing a lot of flexibility for the future.

**Comment by joleroi** [comment]
:+1:  for the 'TAG' option

**Comment by TarekHC** [comment]
I personally don't like the TAG option because it has never been used with FITS files (that I know... any example?). ``HDUCLASn`` has been used by many experiments extending the FITS file format.

An example (from ftp://legacy.gsfc.nasa.gov/fits_info/ofwg_recomm/hduclas.list):


	RESPONSE						Conforms to "The OGIP RMF
									& ARF File Formats",
									George et al. 1992

			EBOUNDS					specifies energy boundaries
									for response matrix.

			SPECRESP				extension contains spectral
									response vs. energy

 	 		RSP_MATRIX	REDIST		"Pure" redistribution matrix
  									w/o anything else folded in

						FULL		Redist matrix with "everything"
									folded in

 						DETECTOR 	Redist matrix with all detector
									components folded in (but NOT
									XRT + Filters).

I don't see many differences between what we want to do and what is done here... But of course, if everyone agrees to use a ``TAGS`` keyword, I would be ok with it.

**Comment by TarekHC** [comment]
Not sure if you are aware, but a team was created to share data between the 3 main IACT experiments to study LIV. There was a meeting held here in Barcelona, and there seems to be an interest to use a common format to share data. As it is just AGN flares data, they don't really need IRF vs FoV, just the minimum required for a classical "point-like analysis". 

Would it make sense to encourage them to use this point-like format? Or is it still too preliminary? I think it would be ideal to have feedback from a real science use case perfective.

**Comment by TarekHC** [comment]
Hi @cdeil , @bkhelifi,

In the last few weeks, I have been thinking about this "point-like DL3 files". For 95% of extragalactic use cases this would be enough, and dramatically simplifies IRF calculation. I have some questions:

* I guess we want to support point-source IRFs of different sources within the same field of view. Then we would need to add keywords within each IRF HDU denoting which source those IRFs are referring to (or simply a 'point-like' and the coordinates wrt the center of the FoV ¿?)

* For the simplest use case of just a point-like source (e.g. just one AGN in our FoV) does it make sense to store the whole FoV within the event list? Or could we allow to already apply the direction cut maximizing sensitivity?

Is there any sample file of a "point-like DL3 file" that you have available? I could have a MAGIC DL3 converter ready in a short time, and also write the proposal within GitHub. Maybe we could have some discussion regarding this topic during the next DL3 telcon?

Cheers and happy new year!

**Comment by jknodlseder** [comment]
I think the classical XSPEC ARF format is well suited for a point-like IRF format. And it can be "easily" derived from the generic IRF format (I put "easily" in quotes since it includes the theta-cut efficiency that can be derived from the PSF variation over the region of interest)

**Comment by cdeil** [comment]
Adding point-source responses in FITS has become a high priority for CTA.

@TarekHC - Are you available to propose a pull request for the spec about how to store it in the coming days?

@jknodlseder - Just using XSPEC ARF is not an option here. We have the FOV dependence, and for analysis there also has to be the information about the energy-dependent THETA cut.

cc @jknodlseder @gernotmaier

**Comment by TarekHC** [comment]
@cdeil I think this topic is now closed with #79 

If anyone does not agree with the solution implemented, re-open the issue.
