### ISSUE TITLE
HDU index table

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#8]
@mimayer I've done some changes to the HDU index table spec:
http://gamma-astro-data-formats.readthedocs.org/en/latest/data_storage/hdu_index/index.html

Any objections so far?

The main thing that's missing is linking to the HDU format spec pages, but those still need to be written.
And I'd like to think a bit more and re-discuss the `BASE_DIR` idea.

**Comment by mimayer** [comment]
I forgot to mention in the docs, that for ctools we currently need "EVENTS" and "GTI" to be contained in the same file (quickly judging from the code). I will add this to the disclaimer.

The header keywords section is still not formatted. I wanted to propose to add the keyword "NAME" or "PRODNAME" to specify the production (e.g. hess-hap-hd-prod01-std_zeta_fullEnclosure). It would a) simplify the creation of the master index file and b) also allows to circumvent the master index file (by indexing the stuff during runtime).
Does that seem ok?

> And I'd like to think a bit more and re-discuss the BASE_DIR idea.

I think this is nice to have. Nevertheless, the absolut path changes as soon the user copies the file over. I.e. when I create FITS files in Zeuthen and rsync them to HD I won't be able to change BASE_DIR immediately. Of course eventually gammapy (or other) scripts can take care of changing this. 
In my view, we could additionally have a keyword "ENVIRON" or "ENV_DIR" to specify the environment variable which replaces BASE_DIR, if BASE_DIR is not available. E.g. ENV_DIR="VHEFTS"?

**Comment by cdeil** [comment]
@mimayer - Feel free to make changes to the event list spec, I haven't even started to review that in detail.

Concerning GTI: can we make it optional? Is it optional in OGIP?

It's only useful for data quality selection, not analysis. Analysis needs LIVETIME.

Not having a GTI makes it easier to have "merged" event lists for all runs ... this is something that I'll propose once the basic specs are through ...

Concerning BASE_DIR: Agreed that having it in the file is problematic, because then it needs updating when copied from the server. Probably what you suggested before, to handle this in the master index file, is better. If you have time, feel free to continue with the master index file spec and put such comments / info about BASE_DIR there (and link to it from the start of the HDU index spec in a comment).

**Comment by cdeil** [comment]
@mimayer - If you have a few more days to change things in Gammalib / ctools, IMO adding HDU name to the IRF load methods would be priority number 1 ... it was super annoying when I wanted to test Gammapy against Gammalib and it wasn't possible to load an IRF file in Gammalib just because the HDU name wasn't correct, requiring a temp copy of the file with a renamed HDU.

**Comment by mimayer** [comment]
> Concerning GTI: can we make it optional? Is it optional in OGIP? It's only useful for data quality selection, not analysis. Analysis needs LIVETIME.

No, the GTIs are needed for analyses in ctools. As far as I know, events time stamps need to be contained in a GTI, otherwise they will be rejected at some point I guess.

**Comment by mimayer** [comment]
What do you think about "PRODNAME" in the header of the hdu-index file?

> @mimayer - If you have a few more days to change things in Gammalib / ctools, IMO adding HDU name to the IRF load methods would be priority number 1 ... it was super annoying when I wanted to test Gammapy against Gammalib and it wasn't possible to load an IRF file in Gammalib just because the HDU name wasn't correct, requiring a temp copy of the file with a renamed HDU.

Well I think in general IRF response tables are loaded as a whole and access is by number of parameter cube. I am not sure how this is done internally and changing the access is probably too fundamental to make a quick shot.

**Comment by mimayer** [comment]
> No, the GTIs are needed for analyses in ctools. As far as I know, events time stamps need to be contained in a GTI, otherwise they will be rejected at some point I guess.

Not sure this is actually true. But certainly GTIs need to be present to read the events from file.

**Comment by cdeil** [comment]
Concerning Prodname: http://gamma-astro-data-formats.readthedocs.org/en/latest/data_storage/hdu_index/index.html#header-keywords

It's a bit cryptic what a "prod" or "production" is.
For this to be understandable you should link to a description in the high-level index page or the [glossary](http://gamma-astro-data-formats.readthedocs.org/en/latest/info/glossary.html).
As I said, I feel we don't have a great concept yet for handling multiple "prods" and don't want to commit to something.

I guess you want this header key to be required, because you want to depend on it in your scripts that handle multiple prods?

**Comment by cdeil** [comment]
Concerning Gammalib / ctools ... here's what I meant:
https://cta-redmine.irap.omp.eu/issues/1596
https://cta-redmine.irap.omp.eu/issues/1597

Hopefully this can be added in the coming days and go in 1.0 and this disclaimer can be removed from our spec:
http://gamma-astro-data-formats.readthedocs.org/en/latest/data_storage/hdu_index/index.html#header-keywords

**Comment by mimayer** [comment]
> I guess you want this header key to be required, because you want to depend on it in your scripts that handle multiple prods?

I think until we have a clear concept of a master index file, we need something to specify cut config, fits prod etc. If we don't want to do this by folder structure, yes, I would need that for the scripts. How should the user then be able to specify the prod?
Proposal: Make it required for the first version and maybe remove it for the future versions when we have a proper idea about the master index file?

**Comment by cdeil** [comment]
>> I guess you want this header key to be required, because you want to depend on it in your scripts that handle multiple prods?

> I think until we have a clear concept of a master index file, we need something to specify cut config, fits prod etc. If we don't want to do this by folder structure, yes, I would need that for the scripts. How should the user then be able to specify the prod?
Proposal: Make it required for the first version and maybe remove it for the future versions when we have a proper idea about the master index file?

No, this is bad. If you're using it in scripts that are in ctools 1.0 you'll never agree to remove it.
It's also very hard to come up with good and unique names at this level, especially in HESS with three prod producers and many prods occuring over the next years.

Let's do this: you go ahead with the spec for the high-level index file as you like it and use it for ctools 1.0. IMO something like "PRODNAME", i.e. a single string is super convenient to have in end-user scripts. That's exactly what we have in the Gammapy DataManager and YAML file format now ... there it's called "name".
The advantage of specifying a version of the high-level index file now is that we can replace it by something else in the future, leaving the old version alone.

I'll try to give feedback on the spec (starting with your proposal B) as time permits over the coming days.

OK?

**Comment by mimayer** [comment]
> If you're using it in scripts that are in ctools 1.0 you'll never agree to remove it.

Not so nice allegation - but thanks.

But ok, I will further think about the spec and update it.

**Comment by cdeil** [comment]
>> If you're using it in scripts that are in ctools 1.0 you'll never agree to remove it.

> Not so nice allegation - but thanks.

It can be considered a compliment.
The main point of writing data format specs is to have an agreed and stable baseline, so it would be weird if we change them in a way that breaks 1.0 software a few months later, right?

**Comment by mimayer** [comment]
Have a look at the master index proposal B.

**Comment by cdeil** [comment]
Master index table:

- Remove proposal A (we'll still use a YAML config file in Gammapy and have as one piece of info where this master index file is located, but I see advantages to us also using the master index file you propose, so it's different and not a competing proposal any more).
- Can we make it a JSON file instead of FITS? It's at least as easy to read for everyone, plus it's human editable.
- Do we really need to specify an environment variable where the file is located? In Gammapy I think I prefer to use a config file for this and other info instead of environment variables, so I'd prefer a simpler spec that doesn't talk about environment variables.

I'll have other detailed comments, and I think there should be a short description saying that this master index file should be on the server and recommending or at least explaining a way this can be synched to user's machines. But that's optional / might be controversial, so let's discuss later.

**Comment by cdeil** [comment]
Just in case it's not clear, here's examples on how tables can be formatted in JSON and YAML:
http://docs.python-tablib.org/en/latest/
https://github.com/darwin/csv2json

YAML is best to read and write (less quotes, braces, allows comments).
But JSON is still much better than FITS / CSV for this purpose (easier manual editing, meta-data and comments can be added under different keys that are not part of the spec)

**Comment by mimayer** [comment]
> Can we make it a JSON file instead of FITS? It's at least as easy to read for everyone, plus it's human editable.

I don't have much experience with JSON. Can you make an example file, how this would look like?
In my view, the file doesn't have to be human readable, since the tools will take care of reading and setting the possible parameters. But I don't have strong arguments against JSON if it is part of the python standard library, so this could be a good compromise.

> Do we really need to specify an environment variable where the file is located? In Gammapy I think I prefer to use a config file for this and other info instead of environment variables, so I'd prefer a simpler spec that doesn't talk about environment variables.

Not every science tool uses config files. It is much easier for the user if a environment variable is set instead of needing to know where the master index file is located for every analysis run (In PA which doesn't use config files, we have $DST_PATH). I therefore strongly prefer to have an environment variable (you don't have to use environment variables for gammapy). We can also remove the statement of environment variables and I add it somewhere else in the ctools docs and HESS documentation?

> I'll have other detailed comments, and I think there should be a short description saying that this master index file should be on the server and recommending or at least explaining a way this can be synched to user's machines. But that's optional / might be controversial, so let's discuss later.

yes no need to do this now as we don't know what we want exactly.

**Comment by cdeil** [comment]
Yes, I can reformat the spec to JSON. As I said, I think it's good to have a human-readable and -editable file for this.

Concerning the environment variable: you should document it in ctools if you use it there.
As I said, IMO there's no reason to make it part of the spec.

**Comment by mimayer** [comment]
Ok

**Comment by cdeil** [comment]
@mimayer - As far as I know Gammalib / ctools now works with arbitrary HDU names for the IRFs and this should be updated:
http://gamma-astro-data-formats.readthedocs.org/en/latest/data_storage/hdu_index/index.html#disclaimer-about-hduname

Should we just drop that section completely?
Or should we keep recommendations on HDU names?
To me, the most logical thing would be to recommend `HDU_TYPE` or `HDU_CLASS`, and not some other third string like "POINT SPREAD FUNCTION".

**Comment by mimayer** [comment]
You are right, we can remove this disclaimer. However, only for event lists we still need an "EVENTS" keyword. I am still working on this: https://cta-redmine.irap.omp.eu/issues/1598#change-6784
But I hope that loading events via an arbitrary HDU name should be possible soon.

**Comment by cdeil** [comment]
> You are right, we can remove this disclaimer. 

OK, I'll do this later today.

**Comment by cdeil** [comment]
I removed the EVENTS / GTI disclaimer for ctools in 9535bd7

**Comment by cdeil** [comment]
I removed the HDU name  disclaimer for ctools in 34469ac and replaced it with a recommendation to use `HDU_TYPE` or `HDU_CLASS` as HDU name.

**Comment by cdeil** [comment]
The last comment here is from 2 years ago. I don't know if there's still anything to discuss / change here, or if the current HDU index spec is OK. Closing this issue now. New issues to propose changes / discuss something preferred, but we can also re-open if needed.
