### ISSUE TITLE
Split out GTI and TELARRAY in separate pages

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#9]
Currently GTI and TELARRAY are listed as sub-sections of the event list spec:
http://gamma-astro-data-formats.readthedocs.org/en/latest/events/index.html

They should be split out in separate pages, because they are just as relevant for IRFs as for EVENTS.

For GTIs I'm not sure if we need to have our own page or if we can just link to
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/rates/ogip_93_003/ogip_93_003.html#tth_sEc6.3
where we mention GTIs, or put it in the glossary.

Anyone wants to work on this or should I?

**Comment by joleroi** [comment]
Hi, I can do this. I am just not sure where to put it.

**Comment by cdeil** [comment]
There's some comments I'd like to make about TELARRAY ... this is stuff that's connected to event types and we'll specify this later, so it will be some extra section mentioning TELARRAY for now, but not a really useful spec. I still have to think what exactly to say and where it fits ... assigning this issue to me.

**Comment by cdeil** [comment]
Looks like this was done already.
GTI is on a separate page: http://gamma-astro-data-formats.readthedocs.io/en/latest/events/gti.html
TELARRAY isn't there any more. Probably removed because it's not needed by science tools, i.e. isn't DL3, but lower-level.
