### ISSUE TITLE
Define sign of energy bias

### ISSUE THREAD

**Issue by cdeil** [open-gamma-ray-astro/gamma-astro-data-formats#93]
While reviewing https://github.com/gammapy/gammapy/pull/1138 by @joleroi I noticed that in Gammapy we're currently defining energy bias with an opposite sign to how @gernotmaier defined it in the "CTA IRF" draft document [here](https://forge.in2p3.fr/projects/cta_analysis-and-simulations/repository/changes/DOC/InternalReports/IRFReports/released/v1.0/cta-aswg-IRFreport.pdf).

In Gammapy we currently define energy bias as `E_reco / E_true - 1`, i.e. `bias > 0` if `E_reco > E_true`. This is also how I would have defined it, and I think everyone uses that definition in HESS.
 One publicly visible document I found with Google is https://pos.sissa.it/236/826/pdf (see energy bias curve in Figure 3, right).

In the "CTA IRF" document [here](simulations/repository/changes/DOC/InternalReports/IRFReports/released/v1.0/cta-aswg-IRFreport.pdf) by @gernotmaier from June 2017, I see this definition:
> Ebias: Energy bias (mean of (`1 − E_reco / E_true` )-distribution)

i.e. it's the opposite sign from what we have, `bias < 0` for `E_reco > E_true`.

@gernotmaier - Is this a typo or do you really use that definition in CTA? Is this definition / sign still open for debate at https://forge.in2p3.fr/boards/236/topics/1830 or do you consider it final for CTA e.g. because there's too much history in CTA MC or even publications using that definition?

Do you know what VERITAS  / MAGIC use?

For Fermi-LAT I found https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_LAT_IRFs/IRF_E_dispersion.html with Google, which does define bias parameters, but it's too late for me to decipher the math and figure out which sign they use. Maybe @woodmd you could comment?

I couldn't find a definition for other instruments or OGIP.

It's not something that we have to define here (because energy bias is currently not used in the EDISP formats we define), but still, it is a very common check / performance plot to show the energy bias curve for a given EDISP, so I think there would value documenting it here. In the end the only thing that makes sense it to follow CTA definitions here, but since it's internal we can't reference it from Gammapy.

**Comment by GernotMaier** [comment]
The IRF document is not describing the CTA conventions but what is currently used in the definition of the IRFs in ROOT format.

Energy bias is a not very well defined property and I think we should not use it at all (and therefore not provide a definition).

It was included in the description of the root IRF files, as some analyses provide these histograms.

**Comment by bkhelifi** [comment]
Hi,
There is indeed a definition issue! Thank you to have found it
But I think one can not derive from this definition discussion that one should not use it at all. For example, the Ereco/Etrue function can be used (and used in HESS for some HL analysis) to define the energy threshold/safe energy for the spectral analysis (e.g. Eth when 2*sigma(Ereco/Etrue)=mean(Ereco/Etrue)).
My proposal is then: why not remove the +/-1? and use Ereco/Etrue vs Ereco for the biais?

**Comment by GernotMaier** [comment]
I do not think that we need the energy bias.

One can simply use the energy dispersion matrix and calculate things like the safe energy threshold on the fly. No need to duplicate information.

**Comment by cdeil** [comment]
I'm about to make the v0.2 stable version of the spec, so moving this issue to the v0.3 milestone.

> I do not think that we need the energy bias. One can simply use the energy dispersion matrix and calculate things like the safe energy threshold on the fly. No need to duplicate information.

@GernotMaier - I think there is value in agreeing on a sign in the definition here.

Energy bias is something that is very commonly used to assess energy reconstruction, and is even regularly shown in IACT reconstruction / performance papers. Try to make one plot comparing the energy reconstruction performance of various recos from different IACTs based on the publications from the past years, and you'll see that it would be nice to agree on a sign.

IMO defining
```
bias = E_reco / E_true - 1
```
is very natural, because "zero bias" mean `E_reco = E_true`, and "positive bias" means that "reco > true".

> The IRF document is not describing the CTA conventions but what is currently used in the definition of the IRFs in ROOT format.

Sounds like this is not set in stone yet for CTA.
cc @kosack

**Comment by GernotMaier** [comment]
I think the sign definition is kind of random and I cannot see that one definition is more natural than another. 

I still think it is not necessary, as it contains the same information as the energy migration matrix. Of course, no strong opinion and the 'costs' are probably minimal if you think it is useful and it should be added, please go ahead.

**Comment by MaxNoe** [comment]
> Energy bias is a not very well defined property

Bias is a perfectly well defined statistical property of any estimator.

> I think the sign definition is kind of random

No, bias is defined as: https://en.wikipedia.org/wiki/Bias_of_an_estimator

So the current sign here is the correct one.

We calculate relative bias, so (E_est - E_true) / E_true
